tests:
  succeeds:
    command: exit 1
    exit-code: 1